version: "3"
services:
  db:
    container_name: 'db'
    image: 'postgres'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 'al0957206766'
      POSTGRES_DB: 'cr'

    volumes:
      - cr-data:/var/lib/postgresql/data
    networks:
      - 'mynet'

  app:
    container_name: 'schoolapp'
    image: 'muhammede/pipline:latest'
   # build: .
    restart: 'on-failure'
    ports:
      - '8080:8080'
    environment:
      DB_HOST: 'db'
      DB_USER: 'postgres'
      DB_PASSWORD: 'al0957206766'
      DB_PORT: '5432'
      DB_NAME: 'cr'
    networks:
      - 'mynet'
    depends_on:
      - 'db'
networks:
  mynet:
    external: true
volumes:
  cr-data: